language: go

go:
 - 1.1
 - 1.2
 - 1.3
 - 1.4
 - 1.5
 - 1.6
 - 1.7
 - 1.8
 - 1.9

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

install:
  - glide install golang.org/x/tools/cmd/cover
  - glide install github.com/mattn/goveralls
  - glide install

script:
  - go test -v $(glide novendor)

after_success:
  - if [ "$TRAVIS_GO_VERSION" == "1.9" ]; then go test -v $(glide novendor) -covermode=count -coverprofile=coverage.out; else go test -v ./shodan; fi
  - if [ "$TRAVIS_GO_VERSION" == "1.9" ]; then $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN; fi
