language: go
go:
 - 1.1
 - 1.2
 - 1.3
 - 1.4
 - 1.5
 - 1.6
 - 1.7
 - 1.8
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert
  - go get -v ./shodan
script:
  - if [ "$TRAVIS_GO_VERSION" == "1.8" ]; then go test -v ./shodan -covermode=count -coverprofile=coverage.out; else go test -v ./shodan; fi
  - if [ "$TRAVIS_GO_VERSION" == "1.8" ]; then $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN; fi
