language: go

go:
 - 1.6
 - 1.7
 - 1.8
 - 1.9

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

cache:
  directories:
    - vendor

install:
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/mattn/goveralls
  - glide install

script:
  - go test -v $(glide novendor)
  - if [ "$TRAVIS_GO_VERSION" == "1.9" ]; then go test -v $(glide novendor) -covermode=count -coverprofile=coverage.out; else go test -v ./shodan; fi
  - if [ "$TRAVIS_GO_VERSION" == "1.9" ]; then $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN; fi
