language: go

go:
 - 1.7
 - 1.8
 - 1.9
 - "1.10"

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

cache:
  directories:
    - vendor

install:
  - go get -u github.com/modocache/gover
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/gordonklaus/ineffassign
  - go get -u github.com/client9/misspell/cmd/misspell
  - glide install

script:
  - golint -set_exit_status ./shodan/...
  - ineffassign ./shodan/
  - misspell -error README.md ./shodan/**/*
  - gofmt -l shodan/ | read && echo "Code differs from gofmt's style" 1>&2 && exit 1 || true
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./shodan/

after_success:
  - bash <(curl -s https://codecov.io/bash) -f ./coverage.txt
