version: "{build}"
skip_tags: true
clone_folder: c:\gopath\src\github.com\ns3777k\go-shodan
clone_depth: 1

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.10
  GOBIN: c:\gopath\bin

build: false
deploy: false

install:
  - set PATH=%GOPATH%\bin;C:\gopath\bin;%PATH%
  - go version
  - go env
  - curl -L -o dep.exe https://github.com/golang/dep/releases/download/v0.4.1/dep-windows-amd64.exe
  - dep.exe ensure

test_script:
  - go test -v ./shodan
