version: "{build}"
skip_tags: true
clone_folder: c:\gopath\src\github.com\ns3777k\go-shodan
clone_depth: 1

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.9

build: false
deploy: false

install:
  - set PATH=%GOPATH%\bin;C:\gopath\bin;%PATH%
  - go version
  - go env
  - go get -v github.com/Masterminds/glide
  - glide install

test_script:
  - go test -v ./shodan
